language: ruby
rvm: 2.1

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

install: gem install jekyll html-proofer
script: jekyll build && htmlproof ./_site
